apiVersion: catalog.kubedb.com/v1alpha1
kind: PerconaXtraDBVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 5.7-cluster
  namespace: default
spec:
  db:
    image: kubedb/percona-xtradb-cluster:5.7
  exporter:
    image: kubedb/mysqld-exporter:v0.11.0
  initContainer:
    image: kubedb/busybox
  podSecurityPolicies:
    databasePolicyName: percona-xtradb-db
  stash:
    addon:
      backupTask:
        name: percona-xtradb-backup-5.7.0-v1
      restoreTask:
        name: percona-xtradb-restore-5.7.0-v1
  version: "5.7"
---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PerconaXtraDBVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: "5.7"
  namespace: default
spec:
  db:
    image: kubedb/percona:5.7
  exporter:
    image: kubedb/mysqld-exporter:v0.11.0
  initContainer:
    image: kubedb/busybox
  podSecurityPolicies:
    databasePolicyName: percona-xtradb-db
  stash:
    addon:
      backupTask:
        name: percona-xtradb-backup-5.7.0-v1
      restoreTask:
        name: percona-xtradb-restore-5.7.0-v1
  version: "5.7"
---
