apiVersion: catalog.kubedb.com/v1alpha1
kind: EtcdVersion
metadata:
  name: 3.2.13
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/etcd:v3.2.13'
  exporter:
    image: '{{ .Values.image.registry }}/etcd:v3.2.13'
  version: 3.2.13
