apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: 4.1.4-v1
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/mongo:4.1.4-v1'
  distribution: MongoDB
  exporter:
    image: '{{ .Values.image.registry }}/percona-mongodb-exporter:v0.8.0'
  initContainer:
    image: '{{ .Values.image.registry }}/mongodb-init:4.1.4'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  stash:
    addon:
      backupTask:
        name: mongodb-backup-4.1.4-v5
      restoreTask:
        name: mongodb-restore-4.1.4-v5
  version: 4.1.4

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: 4.1.4
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/mongo:4.1.4'
  deprecated: true
  distribution: MongoDB
  exporter:
    image: '{{ .Values.image.registry }}/percona-mongodb-exporter:v0.8.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  version: 4.1.4
