apiVersion: catalog.kubedb.com/v1alpha1
kind: MemcachedVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 1.5.4-v1
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/memcached:1.5.4-v1'
  exporter:
    image: '{{ .Values.image.registry }}/memcached-exporter:v0.4.1'
  podSecurityPolicies:
    databasePolicyName: memcached-db
  version: 1.5.4

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MemcachedVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 1.5.4
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/memcached:1.5.4'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/operator:0.8.0'
  podSecurityPolicies:
    databasePolicyName: memcached-db
  version: 1.5.4
