apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: "6.3"
  namespace: default
spec:
  authPlugin: SearchGuard
  db:
    image: kubedb/elasticsearch:6.3
  deprecated: true
  exporter:
    image: kubedb/operator:0.8.0
  initContainer:
    image: kubedb/busybox
    yqImage: kubedb/yq:2.4.0
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  tools:
    image: kubedb/elasticsearch-tools:6.3
  version: "6.3"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 6.3-v1
  namespace: default
spec:
  authPlugin: SearchGuard
  db:
    image: kubedb/elasticsearch:6.3-v1
  deprecated: true
  exporter:
    image: kubedb/elasticsearch_exporter:1.0.2
  initContainer:
    image: kubedb/busybox
    yqImage: kubedb/yq:2.4.0
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  tools:
    image: kubedb/elasticsearch-tools:6.3-v2
  version: "6.3"
