apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: 5.7.31-v1
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/mysql:5.7.31-v1'
  distribution: Oracle
  exporter:
    image: '{{ .Values.image.registry }}/mysqld-exporter:v0.11.0'
  initContainer:
    image: '{{ .Values.image.registry }}/toybox:0.8.4'
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  stash:
    addon:
      backupTask:
        name: mysql-backup-5.7.25-v6
      restoreTask:
        name: mysql-restore-5.7.25-v6
  upgradeConstraints:
    denylist:
      groupReplication:
      - < 5.7.31
      standalone:
      - < 5.7.31
  version: 5.7.31

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: 5.7.31
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/mysql:5.7.31'
  deprecated: true
  distribution: Oracle
  exporter:
    image: '{{ .Values.image.registry }}/mysqld-exporter:v0.11.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  upgradeConstraints:
    denylist:
      groupReplication:
      - < 5.7.31
      standalone:
      - < 5.7.31
  version: 5.7.31
