apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: 8.0.21-v1
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/mysql:8.0.21-v1'
  distribution: Oracle
  exporter:
    image: '{{ .Values.image.registry }}/mysqld-exporter:v0.11.0'
  initContainer:
    image: '{{ .Values.image.registry }}/toybox:0.8.4'
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  stash:
    addon:
      backupTask:
        name: mysql-backup-8.0.21
      restoreTask:
        name: mysql-restore-8.0.21
  upgradeConstraints:
    denylist:
      groupReplication:
      - < 8.0.21
      standalone:
      - < 8.0.21
  version: 8.0.21

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: 8.0.21
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/mysql:8.0.21'
  deprecated: true
  distribution: Oracle
  exporter:
    image: '{{ .Values.image.registry }}/mysqld-exporter:v0.11.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  upgradeConstraints:
    denylist:
      groupReplication:
      - < 8.0.21
      standalone:
      - < 8.0.21
  version: 8.0.21
