apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 10.2-v2
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/postgres:10.2-v3'
  exporter:
    image: '{{ .Values.image.registry }}/postgres_exporter:v0.4.7'
  podSecurityPolicies:
    databasePolicyName: postgres-db
  stash:
    addon:
      backupTask:
        name: postgres-backup-10.14.0-v4
      restoreTask:
        name: postgres-restore-10.14.0-v4
  version: "10.2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 10.2-v3
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/postgres:10.2-v4'
  exporter:
    image: '{{ .Values.image.registry }}/postgres_exporter:v0.4.7'
  podSecurityPolicies:
    databasePolicyName: postgres-db
  stash:
    addon:
      backupTask:
        name: postgres-backup-10.14.0-v4
      restoreTask:
        name: postgres-restore-10.14.0-v4
  version: "10.2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 10.2-v4
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/postgres:10.2-v5'
  exporter:
    image: '{{ .Values.image.registry }}/postgres_exporter:v0.4.7'
  podSecurityPolicies:
    databasePolicyName: postgres-db
  stash:
    addon:
      backupTask:
        name: postgres-backup-10.14.0-v4
      restoreTask:
        name: postgres-restore-10.14.0-v4
  version: "10.2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 10.2-v5
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/postgres:10.2-v6'
  exporter:
    image: '{{ .Values.image.registry }}/postgres_exporter:v0.4.7'
  podSecurityPolicies:
    databasePolicyName: postgres-db
  stash:
    addon:
      backupTask:
        name: postgres-backup-10.14.0-v4
      restoreTask:
        name: postgres-restore-10.14.0-v4
  version: "10.2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: "10.2"
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/postgres:10.2'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/operator:0.8.0'
  podSecurityPolicies:
    databasePolicyName: postgres-db
  version: "10.2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 10.2-v1
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/postgres:10.2-v2'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/postgres_exporter:v0.4.6'
  podSecurityPolicies:
    databasePolicyName: postgres-db
  version: "10.2"
