apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: "10.6"
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/postgres:10.6'
  exporter:
    image: '{{ .Values.image.registry }}/postgres_exporter:v0.4.7'
  podSecurityPolicies:
    databasePolicyName: postgres-db
  stash:
    addon:
      backupTask:
        name: postgres-backup-10.14.0-v4
      restoreTask:
        name: postgres-restore-10.14.0-v4
  version: "10.6"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 10.6-v1
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/postgres:10.6-v1'
  exporter:
    image: '{{ .Values.image.registry }}/postgres_exporter:v0.4.7'
  podSecurityPolicies:
    databasePolicyName: postgres-db
  stash:
    addon:
      backupTask:
        name: postgres-backup-10.14.0-v4
      restoreTask:
        name: postgres-restore-10.14.0-v4
  version: "10.6"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 10.6-v2
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/postgres:10.6-v2'
  exporter:
    image: '{{ .Values.image.registry }}/postgres_exporter:v0.4.7'
  podSecurityPolicies:
    databasePolicyName: postgres-db
  stash:
    addon:
      backupTask:
        name: postgres-backup-10.14.0-v4
      restoreTask:
        name: postgres-restore-10.14.0-v4
  version: "10.6"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 10.6-v3
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/postgres:10.6-v3'
  exporter:
    image: '{{ .Values.image.registry }}/postgres_exporter:v0.4.7'
  podSecurityPolicies:
    databasePolicyName: postgres-db
  stash:
    addon:
      backupTask:
        name: postgres-backup-10.14.0-v4
      restoreTask:
        name: postgres-restore-10.14.0-v4
  version: "10.6"
