{{ if and .Values.catalog.mysql (not .Values.skipDeprecated) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: 5
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ .Values.image.registry }}/mysql:5'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/operator:0.8.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  tools:
    image: '{{ .Values.image.registry }}/mysql-tools:5'
  upgradeConstraints:
    allowlist:
      groupReplication:
      - "5"
      standalone:
      - "5"
  version: "5"
{{- end }}

---
{{ if and .Values.catalog.mysql (not .Values.skipDeprecated) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: 5-v1
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ .Values.image.registry }}/mysql:5-v1'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/mysqld-exporter:v0.11.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  tools:
    image: '{{ .Values.image.registry }}/mysql-tools:5-v2'
  upgradeConstraints:
    allowlist:
      groupReplication:
      - "5"
      standalone:
      - "5"
  version: "5"
{{- end }}
