{{ if .Values.catalog.mysql }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: 8.0.3-v2
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ .Values.image.registry }}/mysql:8.0.3-v2'
  exporter:
    image: '{{ .Values.image.registry }}/mysqld-exporter:v0.11.0'
  initContainer:
    image: '{{ .Values.image.registry }}/toybox:0.8.4'
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  stash:
    addon:
      backupTask:
        name: mysql-backup-8.0.3-v6
      restoreTask:
        name: mysql-restore-8.0.3-v6
  tools:
    image: '{{ .Values.image.registry }}/mysql-tools:5.7.25'
  upgradeConstraints:
    allowlist:
      groupReplication:
      - 8.0.3
      standalone:
      - 8.0.3
  version: 8.0.3
{{ end }}

---
{{ if and .Values.catalog.mysql (not .Values.skipDeprecated) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: 8.0-v1
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ .Values.image.registry }}/mysql:8.0-v1'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/mysqld-exporter:v0.11.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  tools:
    image: '{{ .Values.image.registry }}/mysql-tools:8.0-v2'
  upgradeConstraints:
    allowlist:
      groupReplication:
      - 8.0.3
      standalone:
      - 8.0.3
  version: 8.0.3
{{ end }}

---
{{ if and .Values.catalog.mysql (not .Values.skipDeprecated) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: 8.0.3
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ .Values.image.registry }}/mysql:8.0.3'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/mysqld-exporter:v0.11.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  tools:
    image: '{{ .Values.image.registry }}/mysql-tools:8.0.3'
  upgradeConstraints:
    allowlist:
      groupReplication:
      - 8.0.3
      standalone:
      - 8.0.3
  version: 8.0.3
{{ end }}

---
{{ if and .Values.catalog.mysql (not .Values.skipDeprecated) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: 8.0.3-v1
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ .Values.image.registry }}/mysql:8.0.3-v1'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/mysqld-exporter:v0.11.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  tools:
    image: '{{ .Values.image.registry }}/mysql-tools:5.7.25'
  upgradeConstraints:
    allowlist:
      groupReplication:
      - 8.0.3
      standalone:
      - 8.0.3
  version: 8.0.3
{{ end }}
