apiVersion: catalog.kubedb.com/v1alpha1
kind: PerconaXtraDBVersion
metadata:
  name: 5.7-cluster
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/percona-xtradb-cluster:5.7'
  exporter:
    image: '{{ .Values.image.registry }}/mysqld-exporter:v0.11.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
  podSecurityPolicies:
    databasePolicyName: percona-xtradb-db
  stash:
    addon:
      backupTask:
        name: percona-xtradb-backup-5.7.0-v1
      restoreTask:
        name: percona-xtradb-restore-5.7.0-v1
  version: "5.7"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PerconaXtraDBVersion
metadata:
  name: "5.7"
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/percona:5.7'
  exporter:
    image: '{{ .Values.image.registry }}/mysqld-exporter:v0.11.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
  podSecurityPolicies:
    databasePolicyName: percona-xtradb-db
  stash:
    addon:
      backupTask:
        name: percona-xtradb-backup-5.7.0-v1
      restoreTask:
        name: percona-xtradb-restore-5.7.0-v1
  version: "5.7"
