{{ if and .Values.catalog.mongodb (not .Values.skipDeprecated) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: 4.0.10-percona
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ .Values.image.registry }}/percona-server-mongodb:4.0.10'
  exporter:
    image: '{{ .Values.image.registry }}/percona-mongodb-exporter:v0.8.0'
  initContainer:
    image: '{{ .Values.image.registry }}/mongodb-init:4.1'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  stash:
    addon:
      backupTask:
        name: mongodb-backup-4.0.11-v5
      restoreTask:
        name: mongodb-restore-4.0.11-v5
  tools:
    image: '{{ .Values.image.registry }}/mongo-tools:4.1'
  version: 4.0.10
{{- end }}
