{{ if .Values.catalog.mongodb }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: 3.4.17-v1
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ .Values.image.registry }}/mongo:3.4.17-v1'
  exporter:
    image: '{{ .Values.image.registry }}/percona-mongodb-exporter:v0.8.0'
  initContainer:
    image: '{{ .Values.image.registry }}/mongodb-init:4.1'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  stash:
    addon:
      backupTask:
        name: mongodb-backup-3.4.17-v5
      restoreTask:
        name: mongodb-restore-3.4.17-v5
  tools:
    image: '{{ .Values.image.registry }}/mongo-tools:3.4.17'
  version: 3.4.17
{{ end }}

---
{{ if and .Values.catalog.mongodb (not .Values.skipDeprecated) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: 3.4.17
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ .Values.image.registry }}/mongo:3.4.17'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/percona-mongodb-exporter:v0.8.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ .Values.image.registry }}/replication-mode-detector:v0.3.2'
  tools:
    image: '{{ .Values.image.registry }}/mongo-tools:3.4.17'
  version: 3.4.17
{{ end }}
