apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: "4"
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/redis:4'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/operator:0.8.0'
  podSecurityPolicies:
    databasePolicyName: redis-db
  version: "4"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 4-v1
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/redis:4-v1'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/redis_exporter:v0.21.1'
  podSecurityPolicies:
    databasePolicyName: redis-db
  version: "4"
