apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.5"
  namespace: default
spec:
  authPlugin: SearchGuard
  db:
    image: '{{ .Values.image.registry }}/elasticsearch:6.5'
  deprecated: true
  distribution: SearchGuard
  exporter:
    image: '{{ .Values.image.registry }}/elasticsearch_exporter:1.0.2'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
    yqImage: '{{ .Values.image.registry }}/yq:2.4.0'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  version: 6.5.3

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: 6.5.3
  namespace: default
spec:
  authPlugin: SearchGuard
  db:
    image: '{{ .Values.image.registry }}/elasticsearch:6.5.3'
  deprecated: true
  distribution: SearchGuard
  exporter:
    image: '{{ .Values.image.registry }}/elasticsearch_exporter:1.0.2'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
    yqImage: '{{ .Values.image.registry }}/yq:2.4.0'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  version: 6.5.3
