apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 6.4.0
  namespace: default
spec:
  authPlugin: SearchGuard
  db:
    image: '{{ .Values.image.registry }}/elasticsearch:6.4.0'
  deprecated: true
  distribution: SearchGuard
  exporter:
    image: '{{ .Values.image.registry }}/elasticsearch_exporter:1.0.2'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
    yqImage: '{{ .Values.image.registry }}/yq:2.4.0'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  version: 6.4.0
