apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.8"
  namespace: default
spec:
  authPlugin: X-Pack
  db:
    image: '{{ .Values.image.registry }}/elasticsearch:6.8'
  deprecated: true
  distribution: ElasticStack
  exporter:
    image: '{{ .Values.image.registry }}/elasticsearch_exporter:1.0.2'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
    yqImage: '{{ .Values.image.registry }}/yq:2.4.0'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  version: 6.8.0

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: 6.8.0
  namespace: default
spec:
  authPlugin: X-Pack
  db:
    image: '{{ .Values.image.registry }}/elasticsearch:6.8'
  deprecated: true
  distribution: ElasticStack
  exporter:
    image: '{{ .Values.image.registry }}/elasticsearch_exporter:1.0.2'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
    yqImage: '{{ .Values.image.registry }}/yq:2.4.0'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  version: 6.8.0
