apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 1.3.0-opendistro
  namespace: default
spec:
  authPlugin: OpenDistro
  db:
    image: '{{ .Values.image.registry }}/elasticsearch:1.3.0-opendistro'
  exporter:
    image: '{{ .Values.image.registry }}/elasticsearch_exporter:1.1.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox:1.32.0'
    yqImage: '{{ .Values.image.registry }}/elasticsearch-init:1.3.0-opendistro'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  stash:
    addon:
      backupTask:
        name: elasticsearch-backup-7.3.2-v6
      restoreTask:
        name: elasticsearch-restore-7.3.2-v6
  version: 7.3.2

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 1.3.0-opendistro-v1
  namespace: default
spec:
  authPlugin: OpenDistro
  db:
    image: '{{ .Values.image.registry }}/elasticsearch:1.3.0-opendistro'
  exporter:
    image: '{{ .Values.image.registry }}/elasticsearch_exporter:1.1.0'
  initContainer:
    image: '{{ .Values.image.registry }}/toybox:0.8.4'
    yqImage: '{{ .Values.image.registry }}/elasticsearch-init:1.3.0-opendistro-v1'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  stash:
    addon:
      backupTask:
        name: elasticsearch-backup-7.3.2-v6
      restoreTask:
        name: elasticsearch-restore-7.3.2-v6
  version: 7.3.2

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 7.3.2-searchguard
  namespace: default
spec:
  authPlugin: SearchGuard
  db:
    image: '{{ .Values.image.registry }}/elasticsearch:7.3.2-searchguard'
  exporter:
    image: '{{ .Values.image.registry }}/elasticsearch_exporter:1.1.0'
  initContainer:
    image: '{{ .Values.image.registry }}/toybox:0.8.4'
    yqImage: '{{ .Values.image.registry }}/elasticsearch-init:7.3.2-searchguard'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  stash:
    addon:
      backupTask:
        name: elasticsearch-backup-7.3.2-v6
        params:
        - name: args
          value: --match=^(?!searchguard)([a-zA-Z0-9_-]+)$
      restoreTask:
        name: elasticsearch-restore-7.3.2-v6
  version: 7.3.2

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 7.3.2-xpack
  namespace: default
spec:
  authPlugin: X-Pack
  db:
    image: '{{ .Values.image.registry }}/elasticsearch:7.3.2-xpack'
  exporter:
    image: '{{ .Values.image.registry }}/elasticsearch_exporter:1.1.0'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox:1.32.0'
    yqImage: '{{ .Values.image.registry }}/elasticsearch-init:7.3.2-xpack'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  stash:
    addon:
      backupTask:
        name: elasticsearch-backup-7.3.2-v6
      restoreTask:
        name: elasticsearch-restore-7.3.2-v6
  version: 7.3.2

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 7.3.2-xpack-v1
  namespace: default
spec:
  authPlugin: X-Pack
  db:
    image: '{{ .Values.image.registry }}/elasticsearch:7.3.2-xpack'
  exporter:
    image: '{{ .Values.image.registry }}/elasticsearch_exporter:1.1.0'
  initContainer:
    image: '{{ .Values.image.registry }}/toybox:0.8.4'
    yqImage: '{{ .Values.image.registry }}/elasticsearch-init:7.3.2-xpack-v1'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  stash:
    addon:
      backupTask:
        name: elasticsearch-backup-7.3.2-v6
      restoreTask:
        name: elasticsearch-restore-7.3.2-v6
  version: 7.3.2

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: "7.3"
  namespace: default
spec:
  authPlugin: X-Pack
  db:
    image: '{{ .Values.image.registry }}/elasticsearch:7.3'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/elasticsearch_exporter:1.0.2'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
    yqImage: '{{ .Values.image.registry }}/yq:2.4.0'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  tools:
    image: '{{ .Values.image.registry }}/elasticsearch-tools:7.3'
  version: 7.3.2

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 7.3.2
  namespace: default
spec:
  authPlugin: X-Pack
  db:
    image: '{{ .Values.image.registry }}/elasticsearch:7.3.2'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/elasticsearch_exporter:1.0.2'
  initContainer:
    image: '{{ .Values.image.registry }}/busybox'
    yqImage: '{{ .Values.image.registry }}/yq:2.4.0'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  tools:
    image: '{{ .Values.image.registry }}/elasticsearch-tools:7.3.2'
  version: 7.3.2
