apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: 5.0.3-v1
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/redis:5.0.3-v1'
  exporter:
    image: '{{ .Values.image.registry }}/redis_exporter:v0.21.1'
  podSecurityPolicies:
    databasePolicyName: redis-db
  version: 5.0.3

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: 5.0.3
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/redis:5.0.3'
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/redis_exporter:v0.21.1'
  podSecurityPolicies:
    databasePolicyName: redis-db
  version: 5.0.3
