apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 6.0.6
  namespace: default
spec:
  db:
    image: '{{ .Values.image.registry }}/redis:6.0.6'
  exporter:
    image: '{{ .Values.image.registry }}/redis_exporter:1.9.0'
  podSecurityPolicies:
    databasePolicyName: redis-db
  version: 6.0.6
