apiVersion: catalog.kubedb.com/v1alpha1
kind: PgBouncerVersion
metadata:
  name: "1.7"
  namespace: default
spec:
  deprecated: true
  exporter:
    image: '{{ .Values.image.registry }}/pgbouncer_exporter:v0.1.1'
  server:
    image: '{{ .Values.image.registry }}/pgbouncer:1.7'
  version: "1.7"
