{{ if and .Values.catalog.postgres (not .Values.skipDeprecated) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: 11.2
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ .Values.image.registry }}/postgres:11.2'
  exporter:
    image: '{{ .Values.image.registry }}/postgres_exporter:v0.4.7'
  podSecurityPolicies:
    databasePolicyName: postgres-db
  stash:
    addon:
      backupTask:
        name: postgres-backup-11.9.0-v4
      restoreTask:
        name: postgres-restore-11.9.0-v4
  tools:
    image: '{{ .Values.image.registry }}/postgres-tools:11.2'
  version: "11.2"
{{- end }}

---
{{ if and .Values.catalog.postgres (not .Values.skipDeprecated) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: 11.2-v1
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ .Values.image.registry }}/postgres:11.2-v1'
  exporter:
    image: '{{ .Values.image.registry }}/postgres_exporter:v0.4.7'
  podSecurityPolicies:
    databasePolicyName: postgres-db
  stash:
    addon:
      backupTask:
        name: postgres-backup-11.9.0-v4
      restoreTask:
        name: postgres-restore-11.9.0-v4
  tools:
    image: '{{ .Values.image.registry }}/postgres-tools:11.2'
  version: "11.2"
{{- end }}
