apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: "5.7"
  namespace: default
spec:
  db:
    image: kubedb/mysql:5.7
  deprecated: true
  exporter:
    image: kubedb/operator:0.8.0
  initContainer:
    image: kubedb/busybox
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: kubedb/replication-mode-detector:v0.3.2
  tools:
    image: kubedb/mysql-tools:5.7
  upgradeConstraints:
    allowlist:
      groupReplication:
      - "5.7"
      standalone:
      - "5.7"
  version: "5.7"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v0.16.2
    helm.sh/chart: kubedb-catalog-v0.16.2
  name: 5.7-v1
  namespace: default
spec:
  db:
    image: kubedb/mysql:5.7-v1
  deprecated: true
  exporter:
    image: kubedb/mysqld-exporter:v0.11.0
  initContainer:
    image: kubedb/busybox
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: kubedb/replication-mode-detector:v0.3.2
  tools:
    image: kubedb/mysql-tools:5.7-v2
  upgradeConstraints:
    allowlist:
      groupReplication:
      - "5.7"
      standalone:
      - "5.7"
  version: "5.7"
